#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'crazyflie-ros2-simulation','console_scripts','crazyflie_webots_driver'
__requires__ = 'crazyflie-ros2-simulation'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('crazyflie-ros2-simulation', 'console_scripts', 'crazyflie_webots_driver')()
    )
